iommu: fix build error when CONFIG_IOMMU_API is off
virt inclusion
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/I401IF
CVE: NA

------------------------------

When CONFIG_IOMMU_API is off, kernel compile failed with below error:

...
  LD      vmlinux.o
drivers/of/platform.o: In function `iommu_bind_guest_msi':
platform.c:(.text+0x9e): multiple definition of `iommu_bind_guest_msi'
drivers/of/device.o:device.c:(.text+0x122): first defined here
.../repo/srcs/kernel/Makefile:1178: recipe for target 'vmlinux' failed
...

This should be a typo introduced by commit 9db83ab7c29. Simply correct
the stub function to be 'static inline' in header file should be good
enough.

Signed-off-by: Liang Li (Euler) <liliang889@huawei.com>
Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>
Reviewed-by: Kunkun Jiang <jiangkunkun@huawei.com>
Reviewed-by: Hanjun Guo <guohanjun@huawei.com>