Revert "kabi: reserve space for ptp_clock.h"
hulk inclusion
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/I4KFY7?from=project-issue
CVE: NA

-------------------------------

Revert this patch to fix following compile error:

In file included from <command-line>:32:
./usr/include/linux/ptp_clock.h:135:2: error: expected specifier-qualifier-list before ‘KABI_RESERVE’
  KABI_RESERVE(1)
  ^~~~~~~~~~~~
make[2]: *** [usr/include/Makefile:108: usr/include/linux/ptp_clock.hdrtest] Error 1

This reverts commit af9f9bb9d9e9455ab5bfbdcc5d1f7c88edc4fcd7.

Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>
Reviewed-by: Wang ShaoBo <bobo.shaobowang@huawei.com>
Reviewed-by: Cheng Jian <cj.chengjian@huawei.com>