bpftool: Query only cgroup-related attach types
stable inclusion
from stable-v6.6.131
commit 98b303c9bf05dae932efbd71e18d81f6c64f20d8
category: feature
bugzilla: https://atomgit.com/openeuler/kernel/issues/9042

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=98b303c9bf05dae932efbd71e18d81f6c64f20d8

(cherry-pick from OLK-6.6 commit e76bb5eb9641)

--------------------------------

commit 98b303c9bf05dae932efbd71e18d81f6c64f20d8 upstream.

When CONFIG_NETKIT=y,
bpftool-cgroup shows error even if the cgroup's path is correct:

$ bpftool cgroup tree /sys/fs/cgroup
CgroupPath
ID       AttachType      AttachFlags     Name
Error: can't query bpf programs attached to /sys/fs/cgroup: No such device or address

>From strace and kernel tracing, I found netkit returned ENXIO and this command failed.
I think this AttachType(BPF_NETKIT_PRIMARY) is not relevant to cgroup.

bpftool-cgroup should query just only cgroup-related attach types.

v2->v3:
  - removed an unnecessary check

v1->v2:
  - used an array of cgroup attach types

Signed-off-by: Kenta Tada <tadakentaso@gmail.com>
Reviewed-by: Quentin Monnet <qmo@kernel.org>
Link: https://lore.kernel.org/r/20240607111704.6716-1-tadakentaso@gmail.com
Signed-off-by: Alexei Starovoitov <ast@kernel.org>
Conflicts:
    tools/bpf/bpftool/cgroup.c
[Context conflicts.]
Signed-off-by: Xuan Zhong <zhongzuan2@h-partners.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>