ath9k_htc: fix potential out of bounds access with invalid rxstatus->rs_keyix
stable inclusion
from stable-v4.19.247
commit 4bdcf32c965c27f55ccc4ee71c1927131115b0bb
category: bugfix
bugzilla: https://gitee.com/src-openeuler/kernel/issues/IBP32T
CVE: CVE-2022-49503

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=4bdcf32c965c27f55ccc4ee71c1927131115b0bb

--------------------------------

[ Upstream commit 2dc509305cf956381532792cb8dceef2b1504765 ]

The "rxstatus->rs_keyix" eventually gets passed to test_bit() so we need to
ensure that it is within the bitmap.

drivers/net/wireless/ath/ath9k/common.c:46 ath9k_cmn_rx_accept()
error: passing untrusted data 'rx_stats->rs_keyix' to 'test_bit()'

Fixes: 4ed1a8d4a257 ("ath9k_htc: use ath9k_cmn_rx_accept")
Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Acked-by: Toke Høiland-Jørgensen <toke@toke.dk>
Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/20220409061225.GA5447@kili
Signed-off-by: Sasha Levin <sashal@kernel.org>
Conflicts:
	drivers/net/wireless/ath/ath9k/htc_drv_txrx.c
[Fix context conflicts.]
Signed-off-by: Zeng Heng <zengheng4@huawei.com>