Revert "riscv: stacktrace: Disable KASAN checks for non-current tasks"
hulk inclusion
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8883

(cherry-pick from OLK-6.6 commit 3c5677416f8f)

--------------------------------

This reverts commit 3b5c43e23a8c43a202c7cf7357c363a160c33e7d.

Tirui has already backported this commit (See !20507), so revert
this to avoid redefined compilation error:

arch/riscv/kernel/stacktrace.c:38: error: "READ_ONCE_TASK_STACK" redefined [-Werror]
   38 | #define READ_ONCE_TASK_STACK(task, x)                   \
      |
arch/riscv/kernel/stacktrace.c:23: note: this is the location of the previous definition
   23 | #define READ_ONCE_TASK_STACK(task, x)                   \
      |
cc1: all warnings being treated as errors.

Fixes: 3b5c43e23a8c ("riscv: stacktrace: Disable KASAN checks for non-current tasks")
Signed-off-by: Tengda Wu <wutengda2@huawei.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>