kbuild: Fix grep -q waring
hulk inclusion
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/I9SOCR

---------------------------

For some aarch64 environment, grep -q can cause warning:
    error: write on a pipe with no reader

This is caused in compiling when:
    objdump -h kernel/sched/core.o | grep -q __ksymtab

grep -q __ksymtab is equal to grep __ksymtab > /dev/null,
Use the later command to fix above warning.

Signed-off-by: Chen Zhongjin <chenzhongjin@huawei.com>