ACPI/HMAT: Fix compile error when CONFIG_ACPI_HMAT is not enabled
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IAPHFQ

------------------------------------------------

Fix compile error when CONFIG_ACPI_HMAT is not enabled:
j
../drivers/acpi/acpi_memhotplug.c: In function ‘acpi_memory_enable_device’:
../drivers/acpi/acpi_memhotplug.c:236:5: error: implicit declaration of function ‘hmat_restore_target’; did you mean ‘mte_restore_tags’? [-Werror=implicit-function-declaration]
     hmat_restore_target(node);
     ^~~~~~~~~~~~~~~~~~~
     mte_restore_tags

Fixes: 2e1b00fcf1e3 ("ACPI/HMAT: Add missing locality information for hot-added device")
Signed-off-by: Zhang Zekun <zhangzekun11@huawei.com>