hwmon: (occ) Mark occ_init_attribute() as __printf
stable inclusion
from stable-v6.6.124
commit 8c934bafd10b968bc2be9ad83ab99710247ce251
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9193

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=8c934bafd10b968bc2be9ad83ab99710247ce251

(cherry-pick from OLK-6.6 commit b8d6877b3141)

--------------------------------

[ Upstream commit 831a2b27914cc880130ffe8fb8d1e65a5324d07f ]

This is a printf-style function, which gcc -Werror=suggest-attribute=format
correctly points out:

drivers/hwmon/occ/common.c: In function 'occ_init_attribute':
drivers/hwmon/occ/common.c:761:9: error: function 'occ_init_attribute' might be a candidate for 'gnu_printf' format attribute [-Werror=suggest-attribute=format]

Add the attribute to avoid this warning and ensure any incorrect
format strings are detected here.

Fixes: 744c2fe950e9 ("hwmon: (occ) Rework attribute registration for stack usage")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20260203163440.2674340-1-arnd@kernel.org
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 8c934bafd10b968bc2be9ad83ab99710247ce251)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>