mm/vmalloc: fix pud_page compile error on arm32
ascend inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I4EUVI
CVE: NA

------------

The pud_page is not defined in asm/pgtable-2level.h, when we use it by
disabling CONFIG_ARM_LPAE. So this cause compile error like this:

mm/vmalloc.c: In function 'vmalloc_to_page':
include/asm-generic/pgtable-nop4d-hack.h:48:27: error: implicit
declaration of function 'pud_page'; did you mean 'put_page'?
[-Werror=implicit-function-declaration]
                          ^~~~~~~~
Fixes: e02c5b9bddda ("mm/vmalloc: fix vmalloc_to_page for huge vmap mappings")
Signed-off-by: Fang Lijun <fanglijun3@huawei.com>
Reviewed-by: Ding Tianhong <dingtianhong@huawei.com>
Reviewed-by: Hanjun Guo <guohanjun@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>
Reviewed-by: Weilong Chen <chenweilong@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>