net: move to_gnet_bpf_attach_type() to filter.c
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IAGKEX

--------------------------------

When use bcc tools, we met below issue:
[root@localhost tools]# ./tcpconnect
In file included from /virtual/main.c:15:
In file included from include/net/sock.h:59:
include/linux/filter.h:1502:7: error: use of undeclared identifier \
'BPF_GNET_TCP_RECVMSG'; did you mean 'GNET_TCP_RECVMSG'?
        case BPF_GNET_TCP_RECVMSG:
             ^~~~~~~~~~~~~~~~~~~~
             GNET_TCP_RECVMSG
include/linux/filter.h:1491:2: note: 'GNET_TCP_RECVMSG' declared here
        GNET_TCP_RECVMSG = 0,
        ^
This is because we used it in the header file by mistake. Move the
reference to filter.c.

Fixes: 64ba5634c4c6 ("net: add some bpf hooks in tcp stack for network numa relationship")
Fixes: e79b3265e23d ("net: add one bpf prog type for network numa relationship")
Signed-off-by: Liu Jian <liujian56@huawei.com>