nfs/blocklayout: Fix compilation error (`make W=1`) in bl_write_pagelist()
stable inclusion
from stable-v6.6.141
commit a7fd0d0cb43f3b930e31575154feba8b3261e389
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=a7fd0d0cb43f3b930e31575154feba8b3261e389

(cherry-pick from OLK-6.6 commit 627a03089e5f)

--------------------------------

commit a7fd0d0cb43f3b930e31575154feba8b3261e389 upstream.

[ Upstream commit f83c8dda456ce4863f346aa26d88efa276eda35d ]

Clang compiler is not happy about set but unused variable
(when dprintk() is no-op):

.../blocklayout/blocklayout.c:384:9: error: variable 'count' set but not used [-Werror,-Wunused-but-set-variable]

Remove a leftover from the previous cleanup.

Fixes: 3a6fd1f004fc ("pnfs/blocklayout: remove read-modify-write handling in bl_write_pagelist")
Acked-by: Anna Schumaker <anna.schumkaer@oracle.com>
Reviewed-by: Jeff Layton <jlayton@kernel.org>
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: Chuck Lever <chuck.lever@oracle.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Wang Hai <wanghai38@huawei.com>