Revert "!20376 [OLK-6.6] Support 1G hugetlb for CSV3 and other CSV3 optimizations."
hulk inclusion
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9430

--------------------------------

This reverts commit 14e583ccc8af52f03a29ea704970e8e4b28966c2, reversing
changes made to adbe47b6cb32f8ea1644528dc0efce88d043f126.

It introduces a x86_64 check_build error:

In file included from drivers/char/tpm/tpm_hygon.c:18:
./include/linux/psp-hygon.h:51:9: error: redeclaration of enumerator ‘CSV3_CMD_LAUNCH_FINISH_EX’
   51 |         CSV3_CMD_LAUNCH_FINISH_EX               = 0x204,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/psp-hygon.h:48:9: note: previous definition of ‘CSV3_CMD_LAUNCH_FINISH_EX’ with type ‘int’
   48 |         CSV3_CMD_LAUNCH_FINISH_EX               = 0x204,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~

Revert it to avoid compilation issues.

Fixes: 78d3389e7d6b ("crypto: ccp: Define CSV3 LAUNCH_FINISH_EX command id")
Signed-off-by: Tengda Wu <wutengda2@huawei.com>