ptp: fix code indentation issues
mainline inclusion
from mainline-v5.16-rc1
commit 11195bf5a355a5ef048e690f12b90b70b2c42a86
category: bugfix
bugzilla: https://gitee.com/src-openeuler/kernel/issues/I9RBLZ
CVE: CVE-2021-47455

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=11195bf5a355a5ef048e690f12b90b70b2c42a86

---------------------------

This fixes the following checkpatch.pl errors:

ERROR: code indent should use tabs where possible
+^I        if (ptp->pps_source)$

ERROR: code indent should use tabs where possible
+^I                pps_unregister_source(ptp->pps_source);$

ERROR: code indent should use tabs where possible
+^I                kthread_destroy_worker(ptp->kworker);$

Fixes: 4225fea1cb28 ("ptp: Fix possible memory leak in ptp_clock_register()")
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Zheng Yejian <zhengyejian1@huawei.com>
(cherry picked from commit 680da1b0ffb2609200358928cffcd836dbc75646)