spdxcheck.py: Fix a type error
mainline inclusion
from mainline-v6.4-rc2
commit 28c9f3f9a01d954d8357bdb68fbe36255997bf14
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I7E2XC
CVE:NA
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v6.4-rc2&id=28c9f3f9a01d954d8357bdb68fbe36255997bf14

-----------------------------
remove unused variable "col", otherwise there will be a type error as below:

typeerror: not all arguments converted during string formatting

Signed-off-by: Ding Xiang <dingxiang@cmss.chinamobile.com>
Link: https://lore.kernel.org/r/20220114024058.74536-1-dingxiang@cmss.chinamobile.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: zhujun2 <zhujun2_yewu@cmss.chinamobile.com>