pinctrl: bm1880: add missing select GENERIC_PINCONF
stable inclusion
from stable-v6.6.151
commit a583806ae9697edde7087b054008ab80381fdbce
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9792

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=a583806ae9697edde7087b054008ab80381fdbce

(cherry-pick from OLK-6.6 commit 7f6df6d66777)

--------------------------------

commit dad6e107b3cd9d20514e7799b7ad8674f81e3f30 upstream.

drivers/pinctrl/pinctrl-bm1880.c initialises its pinconf_ops with
.is_generic = true, but that field is only present when
CONFIG_GENERIC_PINCONF is enabled (guarded by #ifdef in pinconf.h).
The Kconfig entry for PINCTRL_BM1880 never selects GENERIC_PINCONF,
so any config that enables CONFIG_PINCTRL_BM1880=y without
CONFIG_GENERIC_PINCONF=y fails to compile:

  drivers/pinctrl/pinctrl-bm1880.c:1288:10: error: 'const struct pinconf_ops' has no member named 'is_generic'

Found by randconfig testing on arm64; tinyconfig reproducer below.
Add the missing select to fix the build.

Fixes: 49bd61ebce5f ("pinctrl: Add pinconf support for BM1880 SoC")
Cc: stable@vger.kernel.org
Signed-off-by: Benjamin Boortz <bennib@mailbox.org>
Signed-off-by: Linus Walleij <linusw@kernel.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit a583806ae9697edde7087b054008ab80381fdbce)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>