sched/fair: guard WA_SMT with CONFIG_SCHED_SMT in wake_wide()
hulk inclusion
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8915

(cherry-pick from OLK-6.6 commit ded4c507c55b)

--------------------------------

cpu_smt_mask() is only defined when CONFIG_SCHED_SMT is enabled. On
architectures that lack SMT support (e.g. RISC-V), WA_SMT feature
code in wake_wide() causes a build failure:

  kernel/sched/fair.c:7855: error: implicit declaration of function 'cpu_smt_mask'

Guard the WA_SMT block with #ifdef CONFIG_SCHED_SMT so that on
non-SMT platforms the factor remains unchanged (equivalent to
smt_width=1).

Fixes: 156a823ef79d ("sched/fair: scale wake_wide() threshold by SMT width")
Signed-off-by: Zhang Qiao <zhangqiao22@huawei.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>