cifsd: fix static checker warning from smb_check_perm_dacl()
mainline inclusion
from mainline-5.15-rc1
commit 50355b0b20103a2be39e269a92909fa69f16f2d0
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/I60T7G
CVE: NA

Reference: https://git.kernel.org/torvalds/linux/c/50355b0b2010

-------------------------------

Dan reported static checker warning:

  fs/cifsd/smbacl.c:1140 smb_check_perm_dacl()
  error: we previously assumed 'pntsd' could be null (see line 1137)

This patch validate bounds of pntsd buffer.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Namjae Jeon <namjae.jeon@samsung.com>
Signed-off-by: Steve French <stfrench@microsoft.com>
Signed-off-by: Jason Yan <yanaijie@huawei.com>
Signed-off-by: Zhong Jinghua <zhongjinghua@huawei.com>