arm64: Fix some build errors related to KEXEC
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I575ZA
CVE: NA

-------------------------------------------------------------------------

Fix below build errors:
error: implicit declaration of function ‘reserve_crashkernel_high’
undefined reference to `request_quick_kexec_res'
undefined reference to `reserve_quick_kexec'

1. An empty reserve_crashkernel_high() should be defined when
   CONFIG_KEXEC_CORE is not set.
2. CONFIG_ARM64_PMEM_RESERVE needs to be changed to CONFIG_QUICK_KEXEC.
   This is a mistake.

Fixes: d61f4ca086e9 ("arm64: quick_kexec: Move to stand-alone file")
Fixes: baac34dd89ca ("arm64: kdump: Use page-level mapping for the high memory of crashkernel")
Signed-off-by: Zhen Lei <thunder.leizhen@huawei.com>
Reviewed-by: Hanjun Guo <guohanjun@huawei.com>
Reviewed-by: Kefeng Wang <wangkefeng.wang@huawei.com>
Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>