perf/x86/intel/uncore: Fix iounmap() leak on global_init failure
mainline inclusion
from mainline-v7.0
commit e2a39d1a88f00ed83ebc7a19b7673d4ffd50b173
category: feature
bugzilla: https://atomgit.com/openeuler/kernel/issues/9392
CVE: N/A
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e2a39d1a88f00ed83ebc7a19b7673d4ffd50b173

-------------------------------------

Intel-SIG: commit e2a39d1a88f0 ("perf/x86/intel/uncore: Fix iounmap() leak on global_init failure")

-------------------------------------

perf/x86/intel/uncore: Fix iounmap() leak on global_init failure

Kernel test robot reported:

Unverified Error/Warning (likely false positive, kindly check if
interested):
    arch/x86/events/intel/uncore_discovery.c:293:2-8:
    ERROR: missing iounmap; ioremap on line 288 and execution via
    conditional on line 292

If domain->global_init() fails in __parse_discovery_table(), the
ioremap'ed MMIO region is not released before returning, resulting
in an MMIO mapping leak.

Fixes: b575fc0e3357 ("perf/x86/intel/uncore: Add domain global init callback")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Zide Chen <zide.chen@intel.com>
Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
Reviewed-by: Dapeng Mi <dapeng1.mi@linux.intel.com>
Link: https://patch.msgid.link/20260313174050.171704-2-zide.chen@intel.com
Signed-off-by: Quanxian Wang <quanxian.wang@intel.com>