nfsd: fix redeclaration of 'clp' in nfs4_laundromat()
hulk inclusion
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/10070

--------------------------------

Commit db4cef375f33 ("NFSD: Prevent client use-after-free during
delegation revoke") introduced a second declaration of 'clp' in
nfs4_laundromat(), causing a compilation error:

fs/nfsd/nfs4state.c: In function ‘nfs4_laundromat’:
fs/nfsd/nfs4state.c:6325:29: error: redeclaration of ‘clp’ with no linkage
 6325 |         struct nfs4_client *clp;
      |                             ^~~
fs/nfsd/nfs4state.c:6314:29: note: previous declaration of ‘clp’ with type ‘struct nfs4_client *’
 6314 |         struct nfs4_client *clp;
      |                             ^~~

Remove the redundant declaration.

Fixes: db4cef375f33 ("NFSD: Prevent client use-after-free during delegation revoke")
Signed-off-by: Tengda Wu <wutengda2@huawei.com>