LoongArch: Fixed a compilation error caused by issue(I7R4EN)
kylin inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I80PP9
CVE: NA

--------------------------------

Error:

./include/linux/nmi.h: In function ‘trigger_all_cpu_backtrace’:
./arch/loongarch/include/asm/irq.h:42:40: error: void value not ignored as it ought to be
   42 | #define arch_trigger_cpumask_backtrace arch_trigger_cpumask_backtrace
./include/linux/nmi.h:167:16: note: in expansion of macro ‘arch_trigger_cpumask_backtrace’
  167 |         return arch_trigger_cpumask_backtrace(cpu_online_mask, false);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/nmi.h: In function ‘trigger_allbutself_cpu_backtrace’:
./arch/loongarch/include/asm/irq.h:42:40: error: void value not ignored as it ought to be
   42 | #define arch_trigger_cpumask_backtrace arch_trigger_cpumask_backtrace
./include/linux/nmi.h:172:16: note: in expansion of macro ‘arch_trigger_cpumask_backtrace’
  172 |         return arch_trigger_cpumask_backtrace(cpu_online_mask, true);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/nmi.h: In function ‘trigger_cpumask_backtrace’:
./arch/loongarch/include/asm/irq.h:42:40: error: void value not ignored as it ought to be
   42 | #define arch_trigger_cpumask_backtrace arch_trigger_cpumask_backtrace
./include/linux/nmi.h:177:16: note: in expansion of macro ‘arch_trigger_cpumask_backtrace’
  177 |         return arch_trigger_cpumask_backtrace(mask, false);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/nmi.h: In function ‘trigger_single_cpu_backtrace’:
./arch/loongarch/include/asm/irq.h:42:40: error: void value not ignored as it ought to be
   42 | #define arch_trigger_cpumask_backtrace arch_trigger_cpumask_backtrace
./include/linux/nmi.h:182:16: note: in expansion of macro ‘arch_trigger_cpumask_backtrace’
  182 |         return arch_trigger_cpumask_backtrace(cpumask_of(cpu), false);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Supplement the missing loongarch part of the patch(9b5619a3a32f)
to solve the compilation error of the loongarch platform.

Fixes: 9b5619a3a32f ("nmi: backtrace: Allow runtime arch specific override")
Signed-off-by: Yongzhen Zhang <zhangyongzhen@kylinos.cn>