Revert "!21796 [OLK-6.6] x86/mce/zhaoxin: Enable mcelog to decode PCIE, ZDI/ZPI, and DRAM errors"
hulk inclusion
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9160

(cherry-pick from OLK-6.6 commit 5a73509a5282)

--------------------------------

This reverts commit f9b4fa77d0c477fbaebfdebd1259e387b88824da, reversing
changes made to 6bcb72eb0f8795e6d0f89c92d5797672c28ab641.

The commit 6bcb72eb0f87 has introduced a kernel build error:

In function ‘zx_apei_mce_report_mem_error’:
arch/x86/kernel/cpu/mce/apei.c:79:9: error: implicit declaration of function ‘mce_setup’; did you mean ‘memset_p’? [-Werror=implicit-function-declaration]
   79 |         mce_setup(&m);
      |         ^~~~~~~~~
      |         memset_p
arch/x86/kernel/cpu/mce/apei.c:130:17: error: passing argument 1 of ‘mce_log’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  130 |         mce_log(&m);
      |                 ^~
      |                 |
      |                 struct mce *

Temporarily revert to mitigate.

Fixes: 6bcb72eb0f87 ("!21795 [OLK-6.6] efi/cper: Add Zhaoxin mem error decode for KH-50000")
Signed-off-by: Tengda Wu <wutengda2@huawei.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>