sched_ext: Allow dequeue_task_scx to fail
mainline inclusion
from mainline-v6.12-rc1
commit 9ad2861b773d7da1cf3a5a04a4e8f1aa7d092bbb
category: feature
bugzilla: https://atomgit.com/openeuler/kernel/issues/8335
CVE: NA

Reference: https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9ad2861b773d7da1cf3a5a04a4e8f1aa7d092bbb

(cherry-pick from OLK-6.6 commit 0230fd7d2347)

--------------------------------

Since dequeue_task() allowed to fail, there is a compile error:

kernel/sched/ext.c:3630:19: error: initialization of ‘bool (*)(struct rq*, struct task_struct *, int)’ {aka ‘_Bool (*)(struct rq *, struct task_struct *, int)’} from incompatible pointer type ‘void (*)(struct rq*, struct task_struct *, int)’
  3630 |  .dequeue_task  = dequeue_task_scx,
       |                   ^~~~~~~~~~~~~~~~

Allow dequeue_task_scx to fail too.

Fixes: 863ccdbb918a ("sched: Allow sched_class::dequeue_task() to fail")
Signed-off-by: Yipeng Zou <zouyipeng@huawei.com>
Signed-off-by: Tejun Heo <tj@kernel.org>
Conflicts:
	kernel/sched/ext.c
[Context difference, only git am reports conflicts, but git cherry-pick
works good.]
Signed-off-by: Zicheng Qu <quzicheng@huawei.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>