wifi: wilc1000: avoid buffer overflow in WID string configuration
stable inclusion
from stable-v6.6.108
commit 6085291a1a5865d4ad70f0e5812d524ebd5d1711
category: bugfix
bugzilla: https://atomgit.com/src-openeuler/kernel/issues/8192
CVE: CVE-2025-39952

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=6085291a1a5865d4ad70f0e5812d524ebd5d1711

--------------------------------

[ Upstream commit fe9e4d0c39311d0f97b024147a0d155333f388b5 ]

Fix the following copy overflow warning identified by Smatch checker.

 drivers/net/wireless/microchip/wilc1000/wlan_cfg.c:184 wilc_wlan_parse_response_frame()
        error: '__memcpy()' 'cfg->s[i]->str' copy overflow (512 vs 65537)

This patch introduces size check before accessing the memory buffer.
The checks are base on the WID type of received data from the firmware.
For WID string configuration, the size limit is determined by individual
element size in 'struct wilc_cfg_str_vals' that is maintained in 'len' field
of 'struct wilc_cfg_str'.

Conflicts:
	drivers/net/wireless/microchip/wilc1000/wlan_cfg.c
[This patch has context conflicts on OLK-5.10 because the target branch differs from the upstream stable version, especially in the WID_STR length parsing logic. It has been manually backported based on the current OLK-5.10 code, keeping the original info[2] length parsing method and adding destination buffer length validation to prevent a buffer overflow in WID string configuration responses.]

Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
Closes: https://lore.kernel.org/linux-wireless/aLFbr9Yu9j_TQTey@stanley.mountain
Suggested-by: Dan Carpenter <dan.carpenter@linaro.org>
Signed-off-by: Ajay Singh <ajay.kathat@microchip.com>
Link: https://patch.msgid.link/20250829225829.5423-1-ajay.kathat@microchip.com
Signed-off-by: Johannes Berg <johannes.berg@intel.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Liu Rui <dev13201@linx-info.com>