tools: libbpf: fix compiler error
hulk inclusion
category: feature
bugzilla: NA
CVE: NA

-------------------------------------------------

This patch tries to fix follow gcc error:

libbpf.c: In function ‘bpf_prog_type__needs_kver’:
libbpf.c:1495:2: error: enumeration value ‘BPF_PROG_TYPE_FLOW_DISSECTOR’ not handled in switch [-Werror=switch-enum]
 1495 |  switch (type) {
      |  ^~~~~~
libbpf.c:1495:2: error: enumeration value ‘BPF_PROG_TYPE_CGROUP_SYSCTL’ not handled in switch [-Werror=switch-enum]
cc1: all warnings being treated as errors
mv: cannot stat './.libbpf.o.tmp': No such file or directory

Fixes: 4635b0ae4d26 ("tools: sync bpf.h")
Signed-off-by: Yufen Yu <yuyufen@huawei.com>
Reviewed-by: Hou Tao <houtao1@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>