riscv: traps: Add missing linux/nospec.h include
openeuler inclusion
category: bugfix
bugzilla: https://atomgit.com/src-openeuler/kernel/issues/13724

(cherry-pick from OLK-6.6 commit 7d4392a16c4d)

--------------------------------

After porting upstream commit 919b4bd35e1f ("riscv: Sanitize syscall
table indexing under speculation"), the compilation fails with:

  arch/riscv/kernel/traps.c:344:35: error: implicit declaration of
  function 'array_index_nospec' [-Werror=implicit-function-declaration]

The array_index_nospec() macro is defined in linux/nospec.h. In upstream
kernel, this header is indirectly included through linux/uaccess.h which
includes linux/nospec.h (since commit 1f9a8286bc0c). However, this kernel
version does not have that include, causing the build failure.

Fix this by adding the missing linux/nospec.h include directly.

Fixes: 919b4bd35e1f ("riscv: Sanitize syscall table indexing under speculation")
Signed-off-by: Qingshuang Fu <fuqingshuang@kylinos.cn>
Signed-off-by: Wang Hai <wanghai38@huawei.com>