bpf: Remove inline from bpf_do_trace_printk
mainline inclusion
from mainline-v5.9-rc1
commit 0d360d64b01231cdb36e1936de889f308fd9317f
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I4PKDW
CVE: NA

--------------------------------

I get the following error during compilation on my side:
kernel/trace/bpf_trace.c: In function 'bpf_do_trace_printk':
kernel/trace/bpf_trace.c:386:34: error: function 'bpf_do_trace_printk' can never be inlined because it uses variable argument lists
 static inline __printf(1, 0) int bpf_do_trace_printk(const char *fmt, ...)
                                  ^

Fixes: ac5a72ea5c89 ("bpf: Use dedicated bpf_trace_printk event instead of trace_printk()")
Signed-off-by: Stanislav Fomichev <sdf@google.com>
Signed-off-by: Alexei Starovoitov <ast@kernel.org>
Link: https://lore.kernel.org/bpf/20200806182612.1390883-1-sdf@google.com
Signed-off-by: Liu Xinpeng <liuxp11@chinatelecom.cn>	# openEuler_contributor
Signed-off-by: Ctyun Kernel <ctyuncommiter01@chinatelecom.cn>	# openEuler_contributor
Signed-off-by: Pu Lehui <pulehui@huawei.com>
Reviewed-by: Yang Jihong <yangjihong1@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>