tcp: fix one compile error in __inet_hash_connect()
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IARV38

--------------------------------

Fix the below error when disable CONFIG_PROC_SYSCTL compile macro:
aarch64-linux-gnu-ld: net/ipv4/inet_hashtables.o: in \
	function `__inet_hash_connect':
net/ipv4/inet_hashtables.c:759: undefined reference to \
	`sysctl_local_port_allocation'

Fixes: 726c52655f7 ("tcp/dccp: Add another way to allocate local ports in connect()")
Signed-off-by: Liu Jian <liujian56@huawei.com>