wifi: ath9k: use proper statements in conditionals
mainline inclusion
from mainline-v6.2-rc3
commit b7dc753fe33a707379e2254317794a4dad6c0fe2
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ICY4GK
CVE: CVE-2023-53199

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=b7dc753fe33a707379e2254317794a4dad6c0fe2

--------------------------------

New bugfix for "ath9k: htc: clean up statistics macros"
A previous cleanup patch accidentally broke some conditional
expressions by replacing the safe "do {} while (0)" constructs
with empty macros. gcc points this out when extra warnings
are enabled:

drivers/net/wireless/ath/ath9k/hif_usb.c: In function 'ath9k_skb_queue_complete':
drivers/net/wireless/ath/ath9k/hif_usb.c:251:57: error: suggest braces around empty body in an 'else' statement [-Werror=empty-body]
  251 |                         TX_STAT_INC(hif_dev, skb_failed);

Make both sets of macros proper expressions again.

Fixes: d7fc76039b74 ("ath9k: htc: clean up statistics macros")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Toke Høiland-Jørgensen <toke@toke.dk>
Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20221215165553.1950307-1-arnd@kernel.org
Signed-off-by: Ziming Du <duziming2@huawei.com>