net/ipv4: Fix missing raw_init when CONFIG_PROC_FS is disabled
mainline inclusion
from mainline-v5.0
commit 86d1d8b72caf
category: bugfix
bugzilla: 9289
CVE: NA

-------------------------------------------------

Randy reported when CONFIG_PROC_FS is not enabled:
    ld: net/ipv4/af_inet.o: in function `inet_init':
    af_inet.c:(.init.text+0x42d): undefined reference to `raw_init'

Fix by moving the endif up to the end of the proc entries

Fixes: 6897445fb194c ("net: provide a sysctl raw_l3mdev_accept for raw socket lookup with VRFs")
Reported-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Mike Manning <mmanning@vyatta.att-mail.com>
Signed-off-by: David Ahern <dsahern@gmail.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Lin Miaohe <linmiaohe@huawei.com>
Reviewed-by: Keefe LIU <liuqifa@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>