sw64: add missing global __constant_c_memset
Sunway inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I56U83

--------------------------------

This patch fixes undefined reference to __constant_c_memset if
CONFIG_DEEP_MEMSET=y and CONFIG_VGA_CONSOLE=y.

Signed-off-by: He Sheng <hesheng@wxiat.com>

Signed-off-by: Gu Zitao <guzitao@wxiat.com>
Acked-by: Xie XiuQi <xiexiuqi@huawei.com>
Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>