ext4: convert DIV_ROUND_UP to DIV_ROUND_UP_ULL
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I4VAQC?from=project-issue
CVE: NA

--------------------------------

Fix a compile error on arm32 architecture.

 build failed: arm, allmodconfig

 ERROR: modpost: "__aeabi_ldivmod" [fs/ext4/ext4.ko] undefined!
 make[1]: *** [modules-only.symvers] Error 1
 make[1]: *** Deleting file 'modules-only.symvers'
 make: *** [modules] Error 2

Fixes: 356efe60eb78 ("ext4: fix underflow in ext4_max_bitmap_size()")
Signed-off-by: Zhang Yi <yi.zhang@huawei.com>
Reviewed-by: Yang Erkun <yangerkun@huawei.com>
Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>