perf maps: Use a pointer for kmaps
mainline inclusion
from mainline-v5.18
commit 1a97cee604dcbdba6c75984b7227223d599ddf32
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IBBJ27

Reference: https://github.com/torvalds/linux/commit/1a97cee604dcbdba6c75984b7227223d599ddf32

--------------------------------

struct maps is reference counted, using a pointer is more idiomatic.

Committer notes:

Delay:

  maps = machine__kernel_maps(&vmlinux);

To after:

  machine__init(&vmlinux, "", HOST_KERNEL_ID);

To avoid this on f34:

  In file included
    from /var/home/acme/git/perf/tools/perf/util/build-id.h:10,
    from /var/home/acme/git/perf/tools/perf/util/dso.h:13,
    from tests/vmlinux-kallsyms.c:8:
  In function ‘machine__kernel_maps’,
      inlined from ‘test__vmlinux_matches_kallsyms’ at
        tests/vmlinux-kallsyms.c:122:22:
  /var/home/acme/git/perf/tools/perf/util/machine.h:86:23:
    error: ‘vmlinux.kmaps’ is used uninitialized [-Werror=uninitialized]
     86 |         return machine->kmaps;
        |                ~~~~~~~^~~~~~~
  tests/vmlinux-kallsyms.c: In function ‘test__vmlinux_matches_kallsyms’:
  tests/vmlinux-kallsyms.c:121:34: note: ‘vmlinux’ declared here
    121 |         struct machine kallsyms, vmlinux;
        |                                  ^~~~~~~
  cc1: all warnings being treated as errors

Conflict: modified tools/perf/util/machine.c context due to c087e9480cf3 not merge.

Signed-off-by: Ian Rogers <irogers@google.com>
Signed-off-by: langfei <langfei@huawei.com>