bpf: Fix build error: linux/kabi.h: No such file or directory
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I645C7
CVE: NA

--------------------------------

The build error as follows:

In file included from net/bpfilter/main.c:9:
net/bpfilter/../../include/uapi/linux/bpf.h:13:10: fatal error: linux/kabi.h: No such file or directory
   13 | #include <linux/kabi.h>
      |          ^~~~~~~~~~~~~~

kabi.h can not be find in user mode code, so remove
<include/kabi.h> from include/uapi/linux/bpf.h. And
use __GENKSYMS__ to fix kabi break.

Fixes: 876a4b54ad82 ("kabi: test fix kabi for enum bpf_prog_type...")
Signed-off-by: Hui Tang <tanghui20@huawei.com>