KVM: selftests: Fix printf() format goof in SEV smoke test
mainline inclusion
from mainline-v6.14-rc6
commit 3b2d3db368013729fd2167a0d91fec821dba807c
category: feature
bugzilla: https://atomgit.com/openeuler/kernel/issues/126
CVE: NA

Reference: https://github.com/torvalds/linux/commit/3b2d3db368013729fd2167a0d91fec821dba807c

--------------------------------

commit 3b2d3db368013729fd2167a0d91fec821dba807c upstream

Print out the index of mismatching XSAVE bytes using unsigned decimal
format.  Some versions of clang complain about trying to print an integer
as an unsigned char.

  x86/sev_smoke_test.c:55:51: error: format specifies type 'unsigned char'
                                     but the argument has type 'int' [-Werror,-Wformat]

[Backport Changes]

In the current backport, changes intended for
tools/testing/selftests/kvm/x86/sev_smoke_test.c
were instead applied to the equivalent file at
tools/testing/selftests/kvm/x86_64/sev_smoke_test.c, since the
renaming of the directory from x86_64 to x86 has not yet been applied
in the current source tree. Therefore, the necessary changes were made
at the existing equivalent location to maintain compatibility.

Fixes: 8c53183dbaa2 ("selftests: kvm: add test for transferring FPU state into VMSA")
Link: https://lore.kernel.org/r/20250228233852.3855676-1-seanjc@google.com
Signed-off-by: Sean Christopherson <seanjc@google.com>
Signed-off-by: PKumarAditya <PappalaKumar.Aditya@amd.com>
Signed-off-by: PrithivishS <sprithiv@amd.com>