drm/tegra: hdmi: sor: Fix error: variable ‘j’ set but not used
stable inclusion
from stable-v6.6.127
commit e120bae4c56d162f38e23ba67097077bf3e43cdd
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9250

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=e120bae4c56d162f38e23ba67097077bf3e43cdd

--------------------------------

[ Upstream commit 1beee8d0c263b3e239c8d6616e4f8bb700bed658 ]

The variable j is set, however never used in or outside the loop, thus
resulting in dead code.
Building with GCC 16 results in a build error due to
-Werror=unused-but-set-variable= enabled by default.
This patch clean up the dead code and fixes the build error.

Example build log:
drivers/gpu/drm/tegra/sor.c:1867:19: error: variable ‘j’ set but not used [-Werror=unused-but-set-variable=]
 1867 |         size_t i, j;
      |                   ^

Signed-off-by: Brahmajit Das <listout@listout.xyz>
Signed-off-by: Thierry Reding <treding@nvidia.com>
Link: https://lore.kernel.org/r/20250901212020.3757519-1-listout@listout.xyz
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit e120bae4c56d162f38e23ba67097077bf3e43cdd)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>