Revert "crypto: talitos - fix SEC1 32k ahash request limitation"
stable inclusion
from stable-v6.6.145
commit 7c3ba8f490f5b2d2ebb5d69247c774d0d4913a06
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9704

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=7c3ba8f490f5b2d2ebb5d69247c774d0d4913a06

(cherry-pick from OLK-6.6 commit 09e4d44f2192)

--------------------------------

This reverts commit 00463d5f864ae28b7938d5acd0ddd800d5457e8b.
Which was backported without applying upstream
commit 9826d1d6ed5f86cb3d61610b3b1fe31e96a40418 first.

Commit a1b80018b8cec27fc06a8b04a7f8b5f6cfe86eae
was backported to 6.6.y with a866e2b1c65edaee2e1bb1024ee2c761ced335f8
It renames last to last_desc but misses one occurrence which leads to compile errors on mpc85xx

drivers/crypto/talitos.c: In function 'ahash_digest':
drivers/crypto/talitos.c:2204:16: error: 'struct talitos_ahash_req_ctx' has no member named 'last'
 2204 | req_ctx->last = 1;
      |        ^~~~

Instead of renaming req_ctx->last, commit 9826d1d6ed5f8 ("crypto: talitos - stop
using crypto_ahash::init") should be applied.
Ideally before commit 00463d5f864a ("crypto: talitos - fix SEC1 32k ahash
request limitation") to avoid any compilation breakage and ensure correctness of
the code.

Reverting and applying in correct order.

Link: https://lore.kernel.org/all/DIOA24QU02W5.2RSVK05RE7BJK@bootlin.com/
Signed-off-by: Goetz Goerisch <ggoerisch@gmail.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 7c3ba8f490f5b2d2ebb5d69247c774d0d4913a06)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>