PM: tools: Fix sleepgraph syntax error
stable inclusion
from stable-v6.6.4
commit 49036a88865eabfb9b05b6920a86f7726441f2c7
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I8N1WC

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=49036a88865eabfb9b05b6920a86f7726441f2c7

--------------------------------

[ Upstream commit b85e2dab33ce467e8dcf1cb6c0c587132ff17f56 ]

The sleepgraph tool currently fails:

  File "/usr/bin/sleepgraph", line 4155
    or re.match('psci: CPU(?P<cpu>[0-9]*) killed.*', msg)):
                                                         ^
SyntaxError: unmatched ')'

Fixes: 34ea427e01ea ("PM: tools: sleepgraph: Recognize "CPU killed" messages")
Signed-off-by: David Woodhouse <dwmw@amazon.co.uk>
Reviewed-by: Wolfram Sang <wsa@kernel.org>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>