livepatch/config: depends on DEBUG_INFO
euler inclusion
category: bugfix
Bugzilla: 9285/5507
CVE: N/A

----------------------------------------

livepatch depends on CONFIG_DEBUG_INFO=y, which isn't selected by
`make allmodconfig` on arm64, that will cause the next build errors.

In function ‘klp_disable_patch’: kernel/livepatch/core.c:497:8:
error: implicit declaration of function
‘__klp_disable_patch’; did you mean ‘klp_disable_patch’?
[-Werror=implicit-function-declaration]

In function ‘klp_enable_patch’: kernel/livepatch/core.c:706:8:
error: implicit declaration of function ‘__klp_enable_patch’;
did you mean ‘klp_enable_patch’?
[-Werror=implicit-function-declaration]

In function ‘klp_check_calltrace’: arch/arm64/kernel/livepatch.c:126:4:
error: implicit declaration of function ‘show_stack’;
did you mean ‘dump_stack’?
[-Werror=implicit-function-declaration]

fix commit 842d0fd7ce9e ("livepatch/core: allow implementation without
ftrace")

Signed-off-by: Cheng Jian <cj.chengjian@huawei.com>
Reviewed-by: Zhen Lei <thunder.leizhen@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>