sched/fair: Fix build error when CONFIG_QOS_SCHED is not set
kylin inclusion
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9610

--------------------------------

When CONFIG_QOS_SCHED is not set and CONFIG_QOS_SCHED_SMART_GRID=y,
building kernel failed with:

kernel/sched/fair.c:331:36: error: 'hundred_thousand' undeclared here (not in a function)
  331 |                 .extra2         = &hundred_thousand,
      |                                    ^~~~~~~~~~~~~~~~
  CC      kernel/power/hibernate.o

Fix error by making variable hundred_thousand visible under
CONFIG_QOS_SCHED_SMART_GRID. Also, replace one_thousand with
SYSCTL_ONE_THOUSAND to keep consistence.

Fixes: f7c232d3e20a ("smart_grid: introduce smart_grid_strategy_ctrl sysctl")
Signed-off-by: Zhao Mengmeng <zhaomengmeng@kylinos.cn>