apparmor: fix label can not be immediately before a declaration
stable inclusion
from stable-v5.10.261
commit 254ceb4fb09f2916159081e74f3d6c42ffe376b7
category: bugfix
bugzilla: https://atomgit.com/src-openeuler/kernel/issues/18554
CVE: CVE-2026-80619

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=254ceb4fb09f2916159081e74f3d6c42ffe376b7

--------------------------------

[ Upstream commit 1ed40bd525c00d22af666016af9aef7167f8085f ]

Fix error reported by kernel test robot

security/apparmor/policy.c:1381:2: error: a label can only be part of
a statement and a declaration is not a statement

All errors (new ones prefixed by >>):

   security/apparmor/policy.c: In function 'aa_replace_profiles':
>> security/apparmor/policy.c:1381:2: error: a label can only be part
   of a statement and a declaration is not a statement
     ssize_t udata_sz = udata->size;
     ^~~~~

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202606150525.npax8WiH-lkp@intel.com/
Fixes: 7b42f95813dc9 ("apparmor: fix potential UAF in aa_replace_profiles")
Signed-off-by: John Johansen <john.johansen@canonical.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Yi Yang <yiyang13@huawei.com>