Revert "riscv: topology: fix default topology reporting"
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I73HJ0

--------------------------------

This reverts commit 932afc18ba98772fe428505c76160428f93e7bde.

Fix build error in riscv64:
build failed: riscv, allmodconfig

arch/riscv/kernel/smpboot.o: In function `smp_callin':
(.text+0x160): undefined reference to `store_cpu_topology'
arch/riscv/kernel/smpboot.o: In function `smp_prepare_cpus':
(.init.text+0x212): undefined reference to `store_cpu_topology'
make: *** [vmlinux] Error 1

Signed-off-by: Jialin Zhang <zhangjialin11@huawei.com>