alpha: don't reference obsolete termio struct for TC* constants
stable inclusion
from stable-v6.6.121
commit fc220dae3cf8945451b9f4710114e69f804a2727
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9046

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=fc220dae3cf8945451b9f4710114e69f804a2727

(cherry-pick from OLK-6.6 commit 8736d437dc80)

--------------------------------

[ Upstream commit 9aeed9041929812a10a6d693af050846942a1d16 ]

Similar in nature to ab107276607af90b13a5994997e19b7b9731e251. glibc-2.42
drops the legacy termio struct, but the ioctls.h header still defines some
TC* constants in terms of termio (via sizeof). Hardcode the values instead.

This fixes building Python for example, which falls over like:
  ./Modules/termios.c:1119:16: error: invalid application of 'sizeof' to incomplete type 'struct termio'

Link: https://bugs.gentoo.org/961769
Link: https://bugs.gentoo.org/962600
Signed-off-by: Sam James <sam@gentoo.org>
Reviewed-by: Magnus Lindholm <linmag7@gmail.com>
Link: https://lore.kernel.org/r/6ebd3451908785cad53b50ca6bc46cfe9d6bc03c.1764922497.git.sam@gentoo.org
Signed-off-by: Magnus Lindholm <linmag7@gmail.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit fc220dae3cf8945451b9f4710114e69f804a2727)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>