openeuler_defconfig: Enable CONFIG_DEBUG_INFO_BTF
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I4S7DA
CVE: NA

-------------------------------

When compiling bpftool, the following error will occur:

$ make -C tools/bpf/bpftool
...
GEN      vmlinux.h
Error: failed to load BTF from vmlinux: No such file or directory

The reason is that bpftool depends on vmlinux.h, which is generated
from vmlinux's BTF info. Moreover, BTF will provide rich debugging
info for ebpf progs and the eBPF CO-RE feature will strongly depend
on it. So let's turn on this feature.

Signed-off-by: Pu Lehui <pulehui@huawei.com>
Reviewed-by: Kuohai Xu <xukuohai@huawei.com>
Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>