spfc: Fix compile errors when O=xxx is specified
Ramaxel inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I4DBD7
CVE: NA

-----------------------------------------

Fix two compile errors:
1. Compile failed when O=xxx is specified;
2. Compile conflicted when spfc and spnic are compiled in parallel
by -j option because they share some .c files.

make O=tmp -j200  > build.log

In file included from ../drivers/scsi/spfc/hw/spfc_utils.c:4:0:
../drivers/scsi/spfc/hw/spfc_utils.h:7:10: fatal error: unf_type.h: No such file or directory
 #include "unf_type.h"
          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [drivers/scsi/spfc/hw/spfc_utils.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [drivers/scsi/spfc] Error 2
make[3]: *** Waiting for unfinished jobs....
../drivers/net/ethernet/ramaxel/spnic/spnic_sriov.c:9:10: fatal error: sphw_common.h: No such file or directory
 #include "sphw_common.h"
          ^~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Yanling Song <songyl@ramaxel.com>
Reviewed-by: Zhang Lei<zhanglei48@huawei.com>
[zzk: Adjusted commit message]
Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>