arm64: fix compile error when CONFIG_NUMA is disabled
hulk inclusion
category: bugfix
bugzilla: 20208
CVE: NA
---------------------------

When CONFIG_NUMA is disabled, compiling the kernel will print the
following error.
arch/arm64/kernel/acpi.c: In function 'acpi_map_cpu':
arch/arm64/kernel/acpi.c:275:3: error: implicit declaration of function 'numa_add_cpu' [-Werror=implicit-function-declaration]
   numa_add_cpu(cpu);
   ^~~~~~~~~~~~
arch/arm64/kernel/acpi.c: In function 'acpi_unmap_cpu':
arch/arm64/kernel/acpi.c:288:2: error: implicit declaration of function 'numa_clear_node' [-Werror=implicit-function-declaration]
  numa_clear_node(cpu);

This patch define 'numa_clear_node()' as a void function when
CONFIG_NUMA is disabled. Also we need to include "asm/numa.h"
explicitly.

Fixes: 207da09b24 ("arm64: Add CPU hotplug support")
Signed-off-by: Xiongfeng Wang <wangxiongfeng2@huawei.com>
Reviewed-by: Hanjun Guo <guohanjun@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>