net: openvswitch: use div_u64() for 64-by-32 divisions
stable inclusion
from linux-4.19.149
commit 1e6a4232befee0c3dbd201f8a50b5c333498f259

--------------------------------

[ Upstream commit 659d4587fe7233bfdff303744b20d6f41ad04362 ]

Compile the kernel for arm 32 platform, the build warning found.
To fix that, should use div_u64() for divisions.
| net/openvswitch/meter.c:396: undefined reference to `__udivdi3'

[add more commit msg, change reported tag, and use div_u64 instead
of do_div by Tonghao]

Fixes: e57358873bb5d6ca ("net: openvswitch: use u64 for meter bucket")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Tonghao Zhang <xiangxia.m.yue@gmail.com>
Tested-by: Tonghao Zhang <xiangxia.m.yue@gmail.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>

Signed-off-by: Aichun Li <liaichun@huawei.com>
Reviewed-by: wangxiaopeng <wangxiaopeng7@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>