livepatch/core: Fix compile error when CONFIG_JUMP_LABEL closed
hulk inclusion
category: bugfix
bugzilla: 28338/31814
CVE: NA

-----------------------------------------------

CONFIG_JUMP_LABEL depends on CC_HAS_ASM_GOTO, some older
compiler may not support.

if CONFIG_JUMP_LABEL closed, compile error as follow:

    kernel/livepatch/core.c: In function ‘klp_init_object_loaded’:
    kernel/livepatch/core.c:1084:2: error: implicit declaration of
    function ‘jump_label_register’ [-Werror=implicit-function-declaration]
    ret = jump_label_register(patch->mod);
        ^

Fixes: 165e314e05f5 ("livepatch/core: support jump_label")
Signed-off-by: Wang ShaoBo <bobo.shaobowang@huawei.com>
Reviewed-by: Cheng Jian <cj.chengjian@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>