RDMA/hns: Fix a static checker warning for hip08
driver inclusion
category: bugfix
bugzilla: NA
CVE: NA

Dan Carpenter provide a bug report about the patch 6a04aed6afae:
"RDMA/hns: Fix the chip hanging caused by sending mailbox&CMQ
during reset" from Feb 3, 2019, which leads to the
following static checker warning:

drivers/infiniband/hw/hns/hns_roce_qp.c:940 hns_roce_create_qp()
error: passing non negative 2 to ERR_PTR

The number "2" comes from hns_roce_cmq_send(), These should be -EBUSY.

Feature or Bugfix:Bugfix

Signed-off-by: liyangyang (M) <liyangyang20@huawei.com>
Reviewed-by: oulijun <oulijun@huawei.com>
Reviewed-by: liuyixian <liuyixian@huawei.com>
Reviewed-by: Yang Yingliang <yangyingliang@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>