mm: ascend: Fix compilation error of mem_cgroup_from_css()
ascend inclusion
category: bugfix
bugzilla: 46906, https://gitee.com/openeuler/kernel/issues/I4DZ7Q
CVE: NA

-------------------------------------------------

When CONFIG_MEMCG is disabled an CONFIG_MM_OWNER is enabled, we encounter
a compilation error as follows:

mm/hugepage_tuning.c: In function ‘get_mem_cgroup_from_path’:
mm/hugepage_tuning.c:130:8: error: implicit declaration of function
‘mem_cgroup_from_css’; did you mean ‘mem_cgroup_from_obj’?
[-Werror=implicit-function-declaration]
  mcg = mem_cgroup_from_css(of_css(of));
        ^~~~~~~~~~~~~~~~~~~
        mem_cgroup_from_obj
mm/hugepage_tuning.c:130:6: warning: assignment makes pointer from integer
without a cast [-Wint-conversion]
  mcg = mem_cgroup_from_css(of_css(of));

To fix it, let mm_update_next_owner() depend on CONFIG_MEMCG

Fixes: 719e31550652 ("arm64/ascend: Add auto tuning hugepage module")
Signed-off-by: Tang Yizhou <tangyizhou@huawei.com>
Reviewed-by: Kefeng Wang <wangkefeng.wang@huawei.com>
Reviewed-by: Ding Tianhong <dingtianhong@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>