tools: fix implicit declaration of function __ALIGN_KERNEL
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/src-openeuler/kernel/issues/IAQOJ9
CVE: NA

----------------------------------------

After mergerd commit "bitmap: introduce generic optimizedbitmap_size()",
When compiling tools/perf, I encountered the following error. I reverted
the changes that added bitmap_size() in tools/include/linux/bitmap.h.
There are no functional changes.

 error: implicit declaration of function \
	 ‘__ALIGN_KERNEL’ [-Werror=implicit-function-declaration]
 #define ALIGN(x, a)  __ALIGN_KERNEL((x), (a))

Fixes: 9e8111c56a25 ("bitmap: introduce generic optimized bitmap_size()")
Signed-off-by: Long Li <leo.lilong@huawei.com>