x86/paravirt: Fix build due to __text_gen_insn() backport
stable inclusion
from stable-v5.10.214
commit cc6ddd6fa93eb59ac6f63158a6466e45ad0ca94c
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ID1J7D
CVE: NA

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.10.y&id=cc6ddd6fa93eb59ac6f63158a6466e45ad0ca94c

--------------------------------

The Link tag has all the details but basically due to missing upstream
commits, the header which contains __text_gen_insn() is not in the
includes in paravirt.c, leading to:

  arch/x86/kernel/paravirt.c: In function 'paravirt_patch_call':
  arch/x86/kernel/paravirt.c:65:9: error: implicit declaration of function '__text_gen_insn' \
  [-Werror=implicit-function-declaration]
   65 |         __text_gen_insn(insn_buff, CALL_INSN_OPCODE,
      |         ^~~~~~~~~~~~~~~

Add the missing include.

Reported-by: Omar Sandoval <osandov@osandov.com>
Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
Link: https://lore.kernel.org/r/ZeYXvd1-rVkPGvvW@telecaster
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Bowen You <youbowen2@huawei.com>