sched: Add dummy version of sched_group_set_idle()
mainline inclusion
from mainline-v6.12-rc1
commit bdeb868c0ddf04c4777bf651834495baaf4f991b
category: feature
bugzilla:  https://gitee.com/openeuler/kernel/issues/ID7HLY

Reference: https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bdeb868c0ddf04c4777bf651834495baaf4f991b

--------------------------------

Fix the following error when build with CONFIG_GROUP_SCHED_WEIGHT &&
!CONFIG_FAIR_GROUP_SCHED:

kernel/sched/core.c:9634:15: error: implicit declaration of function
'sched_group_set_idle'; did you mean 'scx_group_set_idle'? [-Wimplicit-function-declaration]
  9634 |         ret = sched_group_set_idle(css_tg(css), idle);
       |               ^~~~~~~~~~~~~~~~~~~~
       |               scx_group_set_idle

Fixes: e179e80c5d4f ("sched: Introduce CONFIG_GROUP_SCHED_WEIGHT")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202409220859.UiCAoFOW-lkp@intel.com/
Signed-off-by: Yu Liao <liaoyu15@huawei.com>
Signed-off-by: Tejun Heo <tj@kernel.org>
Signed-off-by: Zicheng Qu <quzicheng@huawei.com>
Signed-off-by: cheliequan <cheliequan@inspur.com>