ipv4: fix uninitialized warnings in fnhe_remove_oldest()
hulk inclusion
category: bugfix
bugzilla: 177871
CVE: NA

-------------------------------------------------

The following warning is falsely reported since commit
e2eea86ca197 (ipv4: make exception cache less predictible):

  error: ‘oldest_p’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
    *oldest_p = oldest->fnhe_next;
    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
  net/ipv4/route.c:602:44: note: ‘oldest_p’ was declared here
    struct fib_nh_exception __rcu **fnhe_p, **oldest_p;

Fix and avoid the alarm.

Signed-off-by: Xu Jia <xujia39@huawei.com>
Reviewed-by: Yue Haibing <yuehaibing@huawei.com>
Reviewed-by: Wei Yongjun <weiyongjun1@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>