apparmor: fix label can not be immediately before a declaration
stable inclusion
from stable-v6.6.145
commit 5feaaa1d34b29f9e86388585b54f85b480d62a3c
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9704

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=5feaaa1d34b29f9e86388585b54f85b480d62a3c

--------------------------------

[ Upstream commit 1ed40bd525c00d22af666016af9aef7167f8085f ]

Fix error reported by kernel test robot

security/apparmor/policy.c:1381:2: error: a label can only be part of
a statement and a declaration is not a statement

All errors (new ones prefixed by >>):

   security/apparmor/policy.c: In function 'aa_replace_profiles':
>> security/apparmor/policy.c:1381:2: error: a label can only be part
   of a statement and a declaration is not a statement
     ssize_t udata_sz = udata->size;
     ^~~~~

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202606150525.npax8WiH-lkp@intel.com/
Fixes: 7b42f95813dc9 ("apparmor: fix potential UAF in aa_replace_profiles")
Signed-off-by: John Johansen <john.johansen@canonical.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 5feaaa1d34b29f9e86388585b54f85b480d62a3c)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>