perf hisi-ptt: Fix header file reference error
driver inclusion
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/9811
CVE: NA

(cherry-pick from OLK-6.6 commit a4d0c3b11fe2)

-----------------------------------------------------------

Fixed the issue where the reference to the unaligned.h herder file in
hisi-ptt-pkt=decoder.c was incorrect.

2026-08-24 11:10:38 util/hisi-ptt-decoder/hisi-ptt-pkt-decoder.c:14:10:
fatal error: linux/unaligned.h: No such file or directory
2026-08-24 11:10:38    14 | #include <linux/unaligned.h>
2026-08-24 11:10:38       |          ^~~~~~~~~~~~~~~~~~~

Fixes: 198e811c0a15 ("!26658 Fix the issue where the endianness of TLP packets captured by PTT for 8DW does not match the expected value.")
Signed-off-by: Sizhe Liu <liusizhe5@huawei.com>
Signed-off-by: Chao Zeng <zc18179036325@163.com>
Signed-off-by: Wang Hai <wanghai38@huawei.com>