net: fix one compile error in net_rship_refresh_timeout()
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IARV38

--------------------------------

Fix the below error when disable CONFIG_PROC_SYSCTL compile macro:
aarch64-linux-gnu-ld: net/ipv4/tcp.o: in function \
	`net_rship_refresh_timeout':
include/net/net_rship.h:92: undefined reference to \
	`net_numa_rship_jiffies'

Fixes: 64ba5634c4c6 ("net: add some bpf hooks in tcp stack for network numa relationship")
Signed-off-by: Liu Jian <liujian56@huawei.com>